# Generated by Django 4.0.6 on 2022-07-10 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_content_post_createdat_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='body',
        ),
    ]
